//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecrypteService.JavaDecryptService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.service.com/", ConfigurationName="JavaDecryptService.DecryptEndPoint")]
    public interface DecryptEndPoint {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément xml de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.service.com/DecryptEndPoint/DecryptOperationRequest", ReplyAction="http://facade.service.com/DecryptEndPoint/DecryptOperationResponse")]
        DecrypteService.JavaDecryptService.DecryptOperationResponse DecryptOperation(DecrypteService.JavaDecryptService.DecryptOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.service.com/DecryptEndPoint/DecryptOperationRequest", ReplyAction="http://facade.service.com/DecryptEndPoint/DecryptOperationResponse")]
        System.Threading.Tasks.Task<DecrypteService.JavaDecryptService.DecryptOperationResponse> DecryptOperationAsync(DecrypteService.JavaDecryptService.DecryptOperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptOperation", Namespace="http://facade.service.com/", Order=0)]
        public DecrypteService.JavaDecryptService.DecryptOperationRequestBody Body;
        
        public DecryptOperationRequest() {
        }
        
        public DecryptOperationRequest(DecrypteService.JavaDecryptService.DecryptOperationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class DecryptOperationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public DecryptOperationRequestBody() {
        }
        
        public DecryptOperationRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptOperationResponse", Namespace="http://facade.service.com/", Order=0)]
        public DecrypteService.JavaDecryptService.DecryptOperationResponseBody Body;
        
        public DecryptOperationResponse() {
        }
        
        public DecryptOperationResponse(DecrypteService.JavaDecryptService.DecryptOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class DecryptOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool acceptedDecrypt;
        
        public DecryptOperationResponseBody() {
        }
        
        public DecryptOperationResponseBody(bool acceptedDecrypt) {
            this.acceptedDecrypt = acceptedDecrypt;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DecryptEndPointChannel : DecrypteService.JavaDecryptService.DecryptEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DecryptEndPointClient : System.ServiceModel.ClientBase<DecrypteService.JavaDecryptService.DecryptEndPoint>, DecrypteService.JavaDecryptService.DecryptEndPoint {
        
        public DecryptEndPointClient() {
        }
        
        public DecryptEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DecryptEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DecrypteService.JavaDecryptService.DecryptOperationResponse DecrypteService.JavaDecryptService.DecryptEndPoint.DecryptOperation(DecrypteService.JavaDecryptService.DecryptOperationRequest request) {
            return base.Channel.DecryptOperation(request);
        }
        
        public bool DecryptOperation(string xml) {
            DecrypteService.JavaDecryptService.DecryptOperationRequest inValue = new DecrypteService.JavaDecryptService.DecryptOperationRequest();
            inValue.Body = new DecrypteService.JavaDecryptService.DecryptOperationRequestBody();
            inValue.Body.xml = xml;
            DecrypteService.JavaDecryptService.DecryptOperationResponse retVal = ((DecrypteService.JavaDecryptService.DecryptEndPoint)(this)).DecryptOperation(inValue);
            return retVal.Body.acceptedDecrypt;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DecrypteService.JavaDecryptService.DecryptOperationResponse> DecrypteService.JavaDecryptService.DecryptEndPoint.DecryptOperationAsync(DecrypteService.JavaDecryptService.DecryptOperationRequest request) {
            return base.Channel.DecryptOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DecrypteService.JavaDecryptService.DecryptOperationResponse> DecryptOperationAsync(string xml) {
            DecrypteService.JavaDecryptService.DecryptOperationRequest inValue = new DecrypteService.JavaDecryptService.DecryptOperationRequest();
            inValue.Body = new DecrypteService.JavaDecryptService.DecryptOperationRequestBody();
            inValue.Body.xml = xml;
            return ((DecrypteService.JavaDecryptService.DecryptEndPoint)(this)).DecryptOperationAsync(inValue);
        }
    }
}
