//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A4WebServiceClient.DecryptService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.service.com/", ConfigurationName="DecryptService.DecryptEndPoint")]
    public interface DecryptEndPoint {
        
        // CODEGEN : Le paramètre 'acceptedDecrypt' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.service.com/DecryptEndPoint/DecryptOperationRequest", ReplyAction="http://facade.service.com/DecryptEndPoint/DecryptOperationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="acceptedDecrypt")]
        A4WebServiceClient.DecryptService.DecryptOperationResponse DecryptOperation(A4WebServiceClient.DecryptService.DecryptOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.service.com/DecryptEndPoint/DecryptOperationRequest", ReplyAction="http://facade.service.com/DecryptEndPoint/DecryptOperationResponse")]
        System.Threading.Tasks.Task<A4WebServiceClient.DecryptService.DecryptOperationResponse> DecryptOperationAsync(A4WebServiceClient.DecryptService.DecryptOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jaxb.dev.java.net/array")]
    public partial class stringArray : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }

        public stringArray() { }

        public stringArray(string[] item)
        {
            this.item = item;
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DecryptOperation", WrapperNamespace="http://facade.service.com/", IsWrapped=true)]
    public partial class DecryptOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.service.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FileDecrypt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public A4WebServiceClient.DecryptService.stringArray[] FileDecrypt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.service.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Token;
        
        public DecryptOperationRequest() {
        }
        
        public DecryptOperationRequest(A4WebServiceClient.DecryptService.stringArray[] FileDecrypt, string Token) {
            this.FileDecrypt = FileDecrypt;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DecryptOperationResponse", WrapperNamespace="http://facade.service.com/", IsWrapped=true)]
    public partial class DecryptOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.service.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool acceptedDecrypt;
        
        public DecryptOperationResponse() {
        }
        
        public DecryptOperationResponse(bool acceptedDecrypt) {
            this.acceptedDecrypt = acceptedDecrypt;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DecryptEndPointChannel : A4WebServiceClient.DecryptService.DecryptEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DecryptEndPointClient : System.ServiceModel.ClientBase<A4WebServiceClient.DecryptService.DecryptEndPoint>, A4WebServiceClient.DecryptService.DecryptEndPoint {
        
        public DecryptEndPointClient() {
        }
        
        public DecryptEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DecryptEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        A4WebServiceClient.DecryptService.DecryptOperationResponse A4WebServiceClient.DecryptService.DecryptEndPoint.DecryptOperation(A4WebServiceClient.DecryptService.DecryptOperationRequest request) {
            return base.Channel.DecryptOperation(request);
        }
        
        public bool DecryptOperation(A4WebServiceClient.DecryptService.stringArray[] FileDecrypt, string Token) {
            A4WebServiceClient.DecryptService.DecryptOperationRequest inValue = new A4WebServiceClient.DecryptService.DecryptOperationRequest();
            inValue.FileDecrypt = FileDecrypt;
            inValue.Token = Token;
            A4WebServiceClient.DecryptService.DecryptOperationResponse retVal = ((A4WebServiceClient.DecryptService.DecryptEndPoint)(this)).DecryptOperation(inValue);
            return retVal.acceptedDecrypt;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<A4WebServiceClient.DecryptService.DecryptOperationResponse> A4WebServiceClient.DecryptService.DecryptEndPoint.DecryptOperationAsync(A4WebServiceClient.DecryptService.DecryptOperationRequest request) {
            return base.Channel.DecryptOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<A4WebServiceClient.DecryptService.DecryptOperationResponse> DecryptOperationAsync(A4WebServiceClient.DecryptService.stringArray[] FileDecrypt, string Token) {
            A4WebServiceClient.DecryptService.DecryptOperationRequest inValue = new A4WebServiceClient.DecryptService.DecryptOperationRequest();
            inValue.FileDecrypt = FileDecrypt;
            inValue.Token = Token;
            return ((A4WebServiceClient.DecryptService.DecryptEndPoint)(this)).DecryptOperationAsync(inValue);
        }
    }
}
